# Coding Our First Neurons

## A single Neuron

![single-neuron](images/Screenshot_20230218_090103.png)

This neuron sums each input multiplied by that input’s weight, then adds the bias.

Lets see it in code:

In [22]:
# neuron

inputs = [1.0, 2.0, 3.0, 2.5] 
weights = [0.2, 0.8, -0.5, 1.0] 
bias = 2.0

output = (inputs[0]*weights[0] + 
          inputs[1]*weights[1] + 
          inputs[2]*weights[2] + 
          inputs[3]*weights[3] + 
          bias)

output

4.8

## A Layer of Neurons

Layers are just groups of neurons. Each neuron in a layer:
* Takes exactly the same input
* Has its own set of weights
* Has its own output

![layer](images/Screenshot_20230216_215212.png)

Thus the output of a layer then becomes a group of outputs from its neurons

Lets see it in code:

In [23]:
# for all neurons
inputs = [1.0, 2.0, 3.0, 2.5] 

# for 1st neuron
weights1 = [0.2, 0.8, -0.5, 1] 
bias1 = 2 

# for 2nd neuron
weights2 = [0.5, -0.91, 0.26, -0.5] 
bias2 = 3 

# for 3rd neuron
weights3 = [-0.26, -0.27, 0.17, 0.87] 
bias3 = 0.5

outputs = [# for 1st neuron
           inputs[0]*weights1[0] + 
           inputs[1]*weights1[1] + 
           inputs[2]*weights1[2] + 
           inputs[3]*weights1[3] + bias1, 
           # for 2nd neuron
           inputs[0]*weights2[0] + 
           inputs[1]*weights2[1] + 
           inputs[2]*weights2[2] + 
           inputs[3]*weights2[3] + bias2, 
           # for 3rd neuron
           inputs[0]*weights3[0] + 
           inputs[1]*weights3[1] + 
           inputs[2]*weights3[2] + 
           inputs[3]*weights3[3] + bias3]

outputs


[4.8, 1.21, 2.385]

Imagine coding a layer with 20 neurons. Using the approach from the code above would be tideous. 

Lets refactor the code to be more dynamic

In [24]:
inputs = [1, 2, 3, 2.5]

# put all the weights togethor as a list of lists
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

# put all the biases togethor as a list
biases = [2, 3, 0.5]

outputs = []

for weight_set, bias in  zip(weights, biases):
    output = 0
    for input, weight in zip(inputs, weight_set):
        output += input*weight
    output +=bias
    outputs.append(output)

outputs

[4.8, 1.21, 2.385]

Now our code can calculate the output of a layer of any number of neurons.

However, python alone doesn't do array math very well. So let's upgrade to **Numpy**💪

# A Single Neuron with NumPy


In [25]:
import numpy as np 

inputs = [1.0, 2.0, 3.0, 2.5] 
weights = [0.2, 0.8, -0.5, 1.0] 
bias = 2.0 

outputs = np.dot(weights, inputs) + bias

outputs

4.8

# A Layer of Neurons with NumPy

In [26]:
inputs = [1.0, 2.0, 3.0, 2.5] 

weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]] 
           
biases = [2.0, 3.0, 0.5] 

layer_outputs = np.dot(weights, inputs) + biases

layer_outputs

array([4.8  , 1.21 , 2.385])

# A Layer of Neurons & Batches of Data

Think of the inputs as samples from our server monitoring scenario. Let’s say you have sensor data for the server with metrics such as:
  * upload rates (⬆️)
  * download rates (⬇️)
  * temperature (🌡️)
  * humidity (💧)

...all organized by time for every 10 minutes.

Each column in a single sample is a value for a feature.

columns => [⬇️, ⬆️, 🌡️, 💧]

In [27]:
# A input batch of 3 samples
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

# A layer of 3 neurons
weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]] 
           
biases = [2.0, 3.0, 0.5] 

layer_outputs = np.dot(inputs, weights) + biases

layer_outputs

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

## Matrix Multiplication

![array-multiplication](images/Screenshot_20230220_081537.png)

Notice that the length of the row in the first array has to match the length of the column of the second array

Going back to our code, you can now see that the rows in `inputs` are of length 4 but the columns in `weigths` are of length 3.

That is why we get the shape error.

To fix this, we need to switch the rows and columns of `weights` so that we can satisfy the above rule. This operation is known as **transposing**

Numpy arrays have a `T` (transpose) attribute that we can use. But first we have to transform `weights` which is currently a python list to a NumPy array.

In [ ]:
# A input batch of 3 samples
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

# A layer of 3 neurons
weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]] 
           
biases = [2.0, 3.0, 0.5] 

layer_outputs = np.dot(inputs, np.array(weights).T) + biases

layer_outputs

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

**NB:**
* When adding the dot product resuslt to `biases`, the biases vector gets added to each row of the result. Let's visualize this

![array-addition](images/Screenshot_20230220_134626.png)

## Multiple Layers

In [42]:
# A input batch of 3 samples
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

# Hidden layer 1 (3 neurons)
weights1 = [[0.2, 0.8, -0.5, 1], 
            [0.5, -0.91, 0.26, -0.5], 
            [-0.26, -0.27, 0.17, 0.87]] 
biases1 = [2.0, 3.0, 0.5] 

# Hidden layer 2 (3 neurons)
weights2 = [[0.1, -0.14, 0.5], 
            [-0.5, 0.12, -0.33], 
            [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights1).T) + biases1

# output from the input layer becomes input for the hidden layer
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

layer2_outputs

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

Let's upgrade our code to use object oriented programming priniciples. 💪

First, lets create a class for a layer

# Layer Class

In [46]:
np.random.seed(0)

class Layer_Dense:
    """
    Parameters
    ----------
    n_inputs : int
        Number of features in a single sample
    n_neurons : int
        Number of neurons
    """
    def __init__(self, n_inputs, n_neurons):
        # we multiply by 0.10 so that we get values between -0.1 and 0.1
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) 
        self.biases = np.zeros(shape=(1, n_neurons))
        pass
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

**NB:**

We create our weights matrix using `randn` and specify a shape of (`n_inputs`, `n_neurons`)

So in our previous multiple layers model, this would result in a `weights` of shape (4,3). However the original weights matrix was (3, 4). 

So why are we setting weights like this in the class?
  * So that we can skip the transpose operation we were doing earlier on

In [40]:
np.random.randn(4, 3)

array([[ 0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982]])

In [41]:
0.10 * np.random.randn(4, 3)

array([[ 0.06536186,  0.08644362, -0.0742165 ],
       [ 0.22697546, -0.14543657,  0.00457585],
       [-0.01871839,  0.15327792,  0.14693588],
       [ 0.01549474,  0.03781625, -0.08877857]])

In [39]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [48]:
X = [[1.0, 2.0, 3.0, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

layer1 = Layer_Dense(n_inputs=4, n_neurons=5)
layer1.forward(inputs=X)
layer1.output

array([[-0.46060065,  0.49553499,  0.08326609, -0.4587313 ,  0.34089788],
       [-1.22200575,  0.36184486,  0.40854986,  0.73857089,  1.16296097],
       [ 0.02889447, -0.05931761, -0.56936475, -0.09750155, -0.03436311]])

In [50]:
layer2 = Layer_Dense(n_inputs=5, n_neurons=2)
layer2.forward(inputs=layer1.output)
layer2.output

array([[ 0.03570317, -0.0702464 ],
       [ 0.086899  ,  0.09347172],
       [-0.02322913, -0.06128466]])